DenverCoder1/github-readme-streak-stats

src/stats.php

This change addresses #12 although is not a complete fix.
For most users this change will have no effect.
In #12, it was brought up that if the dates have been manually changed to earlier dates such as Dec 31, 1969, more requests will be necessary since all years from the first commit until the present need to be checked for commits. The requests time out after a certain amount and not all contribution graphs end up in the count.
What this PR changes is the order in which the requests are made for fetching contribution graphs so that recent contributions are fetched first. This way if the requests time out, it will not affect the current/longest streak and will only be missing data from very long ago.

📅 Reverse direction of calendar fetches

---

src/stats.php

Fixes #22 
Previously, the first commit was calculated by making a request to the public profile and extracting the years mentioned at the bottom of the page.
This method was slow and a bit unreliable at times, so I have decided to change this function to use the GitHub API instead.
The creation date of the user is returned as a property when making a request to `https://api.github.com/users/{user}`.

⚡ Using API to fetch creation year

---

src/demo/css/toggle-dark.css

The theme toggle button now placed on the bottom right corner of the page. This is for the screen size below 600px. The background color of the button is changed to blue color.
Fixes #67 
If you have changed a feature of the stats cards, please describe the tests you made to verify your changes.

Fix(toggle-btn): Theme Toggle Button is Fixed

---

.github/workflows/phpunit-ci-coverage.yml

Changed CI to only run when pushing to main so that when pushing to pull request it doesn't run twice.

☑️ Run CI on PR, push to main, and dispatch

---

src/index.php
src/stats.php
tests/StatsTest.php

When current streak is reset, the date range should be removed.

🐛 Reset current streak endpoints when streak broken

---

src/card.php
src/index.php
src/stats.php
tests/OptionsTest.php
tests/RenderTest.php
tests/StatsTest.php

Commits dates that are far in the future will get ignored so that current streak numbers make more sense.
Fixes #83

Only check 1 day ahead for future commits

---

.github/pull_request_template.md

Updated PR template to mention that running tests is not necessary for documentation updates

🔼 Add line about tests for documentation changes

---

src/demo/js/toggle-dark.js

this PR implements the feature that the theme is set on the user preference in the browser using 
```js
window.matchMedia("(prefers-color-scheme: dark)")
```

set darkmode on userpreference

---

README.md

Badge uses GitHub API search results to count users of the badge in a markdown file

Add badge with user count from search results

---

src/card.php
tests/svg/test_card.svg
tests/svg/test_error_card.svg

replaced dominant-baseline with  dy='0.25em'
Fixes #109

replace dominant-baseline with  dy='0.25em'

---

README.md

Removes the directory comment from the `config.php` code block example due to the `#` character causing php to fail to display the web page.

Remove directory from config.php example

---

README.md
src/card.php
tests/OptionsTest.php
tests/RenderTest.php
tests/expected/test_date_card.svg

Added `date_format` parameter for customizing the format to display dates in.
Fixes #29

feat: Add date_format parameter

---

src/demo/js/script.js

Fixes #136 
* added onChange event to color picker
* Checking if length is 9 and last characters are `FF` -> remove them
* tested initial color and color change for multiple elements
no trailling `FF` when color is fully opaque.

Remove hex value if color is fully opaque

---

src/demo/index.php

If there is no cookie at all (e.g. first start) `$_COOKIE["darkmode"]` is not set and there will be a PHP warning (I have them enabled on my local machine)
warning will be gone after this PR

fix php warning when no cookie

---

.github/FUNDING.yml
src/demo/index.php

Added a Date Format field to allow for customization based on 4 options. Tried to use the text box alternative but it seemed like it would be a better option to use the dropdown and have a text box as one of the Advanced Options if required. No changes have been made to the Advanced Options in this pull request.
Fixes #134

Date Format Customization

---

CONTRIBUTING.md
README.md
composer.json
src/card.php
src/index.php
tests/expected/test_card.svg
tests/expected/test_date_card.svg
tests/expected/test_error_card.svg

This PR will add the ability to output the data as a PNG. In order to make this work you will need to have imagick installed and enabled.
There were a couple of changes that I had to make to the SVG as imagick had some issues regarding the `mask` attribute on the circle and the `dy` attributes on the text. 
In order to fix the mask I added an ellipse after adding the circle. This give the same end result. 
To fix the dy I had to eyeball the metrics generated from the created SVG and PNG. After that I adjusted the `y` attributes in order to align everything again.
Fixes #135

Add ability to output as PNG

---

src/demo/js/script.js

I changed a jscolor configuration where the format was set as HEXA instead of HEX.
Fixes #145

Change the jscolor format to HEX instead of HEXA

---

src/card.php
src/demo/preview.php
src/index.php
src/stats.php
tests/OptionsTest.php
tests/RenderTest.php
tests/StatsTest.php

Attempt to fix png conversion on Heroku by prepending xml tag
Solution found here:
Fixes #149

Attempt to fix png conversion on Heroku by prepending xml tag

---

src/stats.php

IF it's bool false, then throws an error. If has a specific string from an SSL error certificate, throws a different exception.
Fixes #157
- [] I have made corresponding changes to the documentation

Error handling for getGitHubApiResponse

---

src/card.php

This PR will force Imagick to interpet the given SVG as an SVG instead of it trying to understand what it is.
Fixes #149

Force Imagick to interpret the blob as an SVG

---

src/index.php

Fixes #141 
This PR changes the output error to JSON when there is an error and the type is set to json:
```
{
"error": "User could not be found."
}
```

Change output errors as JSON when type set to json

---

src/card.php
src/index.php

Warning - headers getting sent twice #162

---

src/index.php

Updated cache control to allow full caching for up to an hour. Hopefully this should reduce the number of requests made to GitHub and avoid the "No contributions found" error.
Should fix #169

fix: Updates to cache control

---

src/card.php

Defends against XSS through date_format
Fixes #177

fix: Sanitize formatted dates

---

.env.example
.github/workflows/phpunit-ci-coverage.yml
CONTRIBUTING.md
README.md
app.json
src/index.php
src/stats.php
tests/StatsTest.php

Migrates from using undocumented contribution graph SVG endpoints to using the GitHub API v4 (GraphQL) to get the dates containing contributions.
This should hopefully make the cards work more reliably and reduce rate-limiting issues.

fix: Migration to GraphQL API

---

tests/StatsTest.php

Valid username test fails when current streak is 0 since start - end is 1 day, but both 0 and 1 are possible streak lengths.

Fix tests when current streak is 0

---

src/card.php
tests/expected/test_card.svg
tests/expected/test_date_card.svg
tests/expected/test_error_card.svg

Solved issue of background color not masking ring in transparent themes.
Fixes #151 
Fixes #211

fix: Transparent themes fire overlapping ring

---

docs/themes/README.md
src/themes.php

This theme  is suitable for dark theme github, with green purple colors and white text for info.
Fixes #

feat: Add github-green-purple theme

---

src/translations.php

The word "Atualmente" was too big, the translation "Presente" is the same meaning, it's just not used much in São Paulo.

Update Portuguese translations

---

src/translations.php

I'm adding a translation for a Korean developer. 
I am also a Korean developer.
I translated it because Korean developers love the project so much. Thank you. 🙏
I interpreted the word "Streak" as "work that I've been doing." 
So I translated 'Current Streak' into 'Current Continuous Commit Count' and 'Longest Streak' into 'Maximum Continuous Commit Count'.
Fixes #236

Add Korean Translation

---

docs/themes/README.md
src/themes.php

- Add color scheme of `neon_blurange` theme to `themes.php`
- Add `neon_bluerange` to `docs/themes/README.md`
Closes #278

feat: Add neon_blurange theme

---

docs/themes/README.md
src/themes.php

Added new java-dark theme.
The black color and the colors of the Java logo were used.

feat: add java-dark theme

---

src/card.php

Apparently `YYYY` means "Year of 'week of year'" (whatever that means) and this should be using `yyyy` instead.
Fixes #291

fix: Wrong year displayed on cards

---

src/demo/index.php

Moved Locale field above Date format field in the demo site.
This order makes more sense since changing the Locale effects the default setting for date format so should be changed first to know what the default actually will look like. If the date format is changed first, the internationalized date format won't be seen by the user.

fix(demo): Move locale above date format

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/first-run-notice.txt
.devcontainer/on-create.sh
.devcontainer/post-create.sh

This pull requests adds a devcontainer configuration that will be used when a codespace is started in this repository. This configuration installs the packages that are required to run the unit tests of this project. And it also uses the `$GITHUB_TOKEN` variable that is available in a codespaces to create the `.env` file that is used by the unit tests. I have also added a file called `first-run-notice.txt` that will be shown when the codespace is started. It might need some more improvements but I will leave that up to the maintainers of this project.
When trying to get `composer test` to work I also noticed that I needed different packages to make it work. I don't have enough php experience to know what to change in the `composer.json` file or `README.md` so I will leave that up to the …

Added .devcontainer for GitHub Codespaces.

---

src/demo/index.php
src/demo/js/script.js

Change submit button text to say Open Permalink

fix(demo): Change submit button text to say Open Permalink

---

docs/themes.md
src/themes.php

feat: Add sea theme

---

README.md
docs/faq.md
docs/themes.md

It is still hosted on Heroku, just added a new custom domain to make it easier to move the hosting in the future if necessary

docs: Update links to demolab custom domain

---

src/card.php
src/translations.php
tests/TranslationsTest.php
tests/expected/test_border_radius_card.svg
tests/expected/test_card.svg
tests/expected/test_date_card.svg
tests/expected/test_locale_ja_card.svg

Adds Hebrew translations and RTL language support
Thanks u/CherryPepper_1 [on Reddit](https://www.reddit.com/r/translator/comments/y49goi/english_hebrew_total_contributions_current_streak/) for help with the translation
Ref: #236

feat: Added Hebrew translations and RTL language support

---

src/card.php
tests/RenderTest.php
tests/expected/test_border_radius_card.svg
tests/expected/test_card.svg
tests/expected/test_date_card.svg
tests/expected/test_error_card.svg
tests/expected/test_locale_ja_card.svg

Allows for 2-line translations and splits range text at " - " if the line exceeds 28 characters.
Translated labels will automatically split at 22 (bold) / 24 characters.
Newlines may be inserted manually in translations.php to override the max chars effect, eg. `"Total\nContributions"`)
Before
After
Before
After

feat: Wrap long lines and allow for two-line translation strings

---

Aptfile
src/card.php
src/translations.php
tests/RenderTest.php

Previously the wordwrap would cause display issues with text such as "மிக சமீபத்திய தொடர்ச்சியான பங்களிப்புகள்"
This implementation works better with other languages

fix: replace wordwrap to support utf8 words

---

docs/themes.md
src/themes.php

I added the best theme ever!!!!!
Actually it's my personal theme, but I use it all the time and I think it belongs here too.
With the attribute thing in the link

feat: Added modern-lilac and modern-lilac2 themes

---

docs/themes.md
src/themes.php

Added "halloween" theme.
The inspiration comes from the GitHub Halloween contribution graphs that have appeared on October 31 each year.
This is an opt-in theme and can be used by setting the `theme` parameter to `halloween`.

feat: Added "halloween" streak stats theme

---

docs/themes.md
src/themes.php

Hi Jonah,
I was able to successfully edit `themes.php` to add my new theme colors and I brew installed PHP and Composer so I could test my theme locally. It successfully ran and after a couple of additional commits (sorry for making 2 commits for my docs/themes.md entry) and a lot of head scratching I think I was able to finally add my theme correctly! 
Fixes # 350
Added a new theme for GitHub README Streak Stats! 
^ I didn't comment out my code or make changes to the documentation because they aren't applicable here. 
Here's the static PNG image of my theme that I added to `docs/themes.md`

Submarine Flowers Theme

---

src/card.php
tests/expected/test_card.svg
tests/expected/test_error_card.svg

Uses font-family, font-weight, font-size, font-style as SVG attributes rather than in inline CSS
Related: #355

refactor: Use font SVG attributes instead of CSS

---

src/stats.php

Prevents some errors from appearing in the logs

fix: Skip graphs if contribution graph returns null

---

scripts/translation-progress.php

Make progress bars and locales link to line numbers in translations file
Fixes #

docs(readme): Add links to line numbers for locales

---

.gitignore
src/index.php
src/stats.php

Fixes parse error for usernames containing quotes
The username is sanitized to only allow letters, numbers, dashes

fix: Parse error when user passed contains quotes

---

src/demo/preview.php
src/index.php
src/stats.php

NULL was gettng passed as the error message when a GitHub API error occurred while fetching a graph
Fixes #379

fix: API error not passing message

---

src/translations.php

- Better choice of words.
- Added date format.
- Added Week Streak translation.
- Added Longest Week Streak translation.
Ref: #236

feat: Improved Brazilian Portuguese translations

---

src/translations.php

Fixed persian translation for "sequence" and "present"
Fixed persian translation for "sequence" and "present". There was also a switched phrase translation.
The translation looked like it was made by machine translation. 
Ref: #236

Fixed persian translation

---

src/translations.php

1. Rename "chinese"(zh) to "simplified chinese"(zh-Hans)
2. Add "traditional chinese"(zh-Hant)

feat: Added Traditional Chinese translation

---

composer.lock
scripts/translation-progress.php

docs(readme): Use HTML syntax for locale table

---

src/card.php

refactor: Convert to PNG without using files

---

src/stats.php

fix: Only decode json if it's a string

---

src/stats.php

fix: Prevent reusing tokens when rate limited

---

src/translations.php

The translation of `Longest Week Streak` was `Plus longue de semaine séquence`. This is not grammatically correct in French, which is why I propose this fix by replacing it with `Plus longue séquence hebdomadaire`.
- [x ] Bug fix (added a non-breaking change which fixes an issue)

fix: Updated French translation of `Longest Week Streak`

---

src/demo/css/style.css

* fixes tooltip triangle styles
* adjusts cursor when hovering disabled button
Fixes #435 
https://user-images.githubusercontent.com/60817786/215276966-04e69a30-8d5d-4239-9a24-3aa535d4d120.mov

fix(demo): Update tooltip triangle and disabled button cursor

---

src/demo/index.php
src/demo/js/script.js

* maps option colors with default ones
* does not set advanced prop on submit
Fixes #432 
N/A

Do not add advanced prop on submit

---

src/demo/css/style.css
src/demo/index.php
src/demo/js/script.js

* Made id/class naming style consistent
* Make clear button disabled by default (on page load)
* Make details summary show pointer cursor
* Remove redundant return for button click events
* More saturated default color that's a little easier to look at

refactor: Consistent ID naming, redundant return, styling

---

src/stats.php

Filter out years with contributions that are before the user's account creation.
This limits the number of requests for users with backdated commits such as commits on Jan 1, 1970.
Fixes #448

fix: filter years before account creation

---

src/card.php

Allows background and stroke colors specified as "#xxxxxx00" or "#xxx0" to appear transparent instead of black when type is set to PNG. Setting the color to "transparent" works as well.

fix: workaround for transparent background in PNG mode

---

src/card.php
tests/RenderTest.php

Adds support for hex colors in the format #rgba / #rrggbbaa where aa is the opacity (00-FF) when converting to PNG.
Inkscape does not currently support the #rgba / #rrggbbaa syntax - see https://gitlab.com/inkscape/inbox/-/issues/8215
Other SVG renderers may also have issues with certain colors fixed.

fix: Use fill-opacity and stroke-opacity for hex colors with alpha

---

src/demo/css/style.css
src/demo/index.php
src/demo/js/script.js

* Added version timestamps to css/js files to avoid old cached versions
* Removed disable_animations from demo site and replace with "type"
* Added previewing png and json types
* Refactored class names
* Remove global click event listener and run update when picker changed instead

feat(demo): add png/json preview to demo site and refactor

---

docs/themes.md
src/themes.php

Adds the "transparent" theme from [github-readme-stats](https://github.com/anuraghazra/github-readme-stats) to this project to allow for easier theme consistency.
Fixes #206

feat: Add "transparent" theme

---

docs/themes.md
src/themes.php

This theme has bright colors that works well with dark backgrounds.
Fixes #

feat: Added neon theme

---

src/card.php
tests/RenderTest.php
tests/expected/test_card.svg
tests/expected/test_error_card.svg

Swapped locations of total contributions and longest streak for right-to-left languages.
Naturally, when a language is read right to left, the order of elements are reversed.

feat: Swap first and third columns when direction is rtl

---

src/card.php
tests/OptionsTest.php
tests/RenderTest.php
tests/expected/test_card.svg
tests/expected/test_error_card.svg

fix: Apply background gradients on error cards

---

src/translations.php

Pashto was missing `"rtl" => true` even though it is a right to left language.

fix: Updated Pashto to be right-to-left

---

tests/OptionsTest.php
tests/StatsTest.php

ci: Update tests to support gradient themes and test starting year

---

README.md

Change Demo Site link ("http://" to  "https://")  in the Readme file
Fixes  #518

fix: Demo Site link in Readme

---

README.md
src/card.php
src/themes.php
tests/OptionsTest.php
tests/RenderTest.php

Fixes #525 
Previously the `dates` color was used for the excluded days label. Those who override the dates color with the `dates` query parameter will need to also add `excludeDaysLabel` with the same value. Use of theme names is not affected.

feat!: Add color customization for excludeDaysLabel

---

src/translations.php

- Shortened and more accurate brazilian translation from `Total Contributions`;
- Excluding translation - Was translated as `Except`
***Total de Contribuições*** is correct but i think ***Contribuições Totais*** is way better because it removes preposition ***de***.
**Excluding** in this context is with meaning of **Except** in pt-BR. So the accurate way to translate **Excluding** is ***Exceto***.
- https://translate.google.com.br/?hl=pt-BR&sl=en&tl=pt&text=total%20contributions&op=translate
- https://translate.google.com.br/?hl=pt-BR&sl=en&tl=pt&text=except&op=translate

feat: Update Brazilian Portuguese translations

---

src/translations.php

feat: Updated Dutch translations

---

README.md

docs(readme): Add deploy buttons near the top of the readme

---

src/card.php

This makes the command all on a single line which may make PNG work better (#596) or at least make reading the logs easier

fix: Replace newline with space when converting SVG to PNG

---

scripts/translation-progress.php
src/card.php
src/translations.php
tests/TranslationsTest.php

* Adds support for putting the days before or within the translation for Excluding {days}
* Adds support for alternate comma separators ("، " for Arabic, Farsi, Urdu and "、" for Chinese, "・" for Japanese)
* ~~Adds support for overriding the day of week format to long names instead of short for specific locales~~
* Adds Japanese translation for Excluding {days}

feat: Support word order change, comma separation, Japanese for Excluding

---

src/translations.php

Looking at the changes made in #604, it reminded me of the Korean translation for 'excluding.' Similar to Japanese, I modified the translation from the '제외된 날 {dates}' to '{dates} 제외된.' The use of '제외된' would make perfect sense when placed behind the day names. So, even without the word '날,' this sentence already makes sense, considering that before the significant change, we couldn't place '제외된' behind the day names.
_No screenshots_

fix: Updated Korean for Excluding translation

---

src/index.php

chore: Increase cache headers to 3 hours

---

src/demo/js/script.js

Setting the recently removed option as the currently selected one
Fixes #570

fix: demo site color property added twice

---

docs/themes.md

Fixes typos on names in `themes.md` for the Catppuccin collection of themes.
I didn't open an issue since it was a pretty quick fix, but please let me know if I should open one :)
N/A - documentation only :)
N/A - documentation only :)

docs(themes): Fix Catppuccin theme names

---

README.md
src/card.php
src/demo/index.php
src/demo/js/script.js
tests/RenderTest.php
tests/expected/test_card.svg
tests/expected/test_error_card.svg

feat: create height option
- Created input for height option in form (src/demo/index.php)
- Update custom image height in process (src/card.php)
Fixes #659

feat: Added card_height option

---

docs/themes.md
src/themes.php

Adding a theme using the [Dark-Minimalist](https://github.com/LeonN534/Dark-Minimalist) color palette.
Fixes #686

Dark minimalist theme

---

src/translations.php

- Added a Swahili translation for the phrase "Excluding {days}" in the language translations file.
- Ensured consistent formatting and localization standards are maintained.
- Updated the key `"Excluding {days}"` with its Swahili equivalent `"Ukiondoa {days}"`.
Fixes #

Add Swahili translation for "Excluding {days}"

---

docs/themes.md
src/themes.php

Add theme with Microsoft's logo colors both with light and dark backgrounds

feat: add Microsoft themes

---

src/card.php
src/demo/index.php
src/demo/js/script.js
tests/RenderTest.php

Resolves #729 
This pull request introduces a new feature to display large numbers in a shortened format (e.g., 1K for 1,000) on the generated cards. The changes include the implementation of the short number formatting function, updates to the card generation logic, and modifications to the demo interface and tests to support this new feature.
Key changes:
* Added `shortNumber` function in `src/card.php` to convert large numbers into a short form (e.g., 1K, 1M).
* Updated `generateCard` function in `src/card.php` to use the `shortNumber` function when the `short_numbers` parameter is set to "true" [[1]](diffhunk://#diff-1ce15c620155c6dbfb5273d35fed74813bcbf66ce7927d36c291a592f79baa66R440-R452) [[2]](diffhunk://#diff-1ce15c620155c6dbfb5273d35fed74813bcbf66ce7927d36c291a592f79baa66L435-R463 …

feat: Add option to use short number format

---

docs/themes.md
src/themes.php

Add `hacker-inverted` theme, it's just inverted version of `hacker` theme

feat: add hacker-inverted theme

---

src/card.php
tests/expected/test_card.svg

sorted svg element

---

docs/themes.md
src/themes.php

Added a new theme Cyber Streak Glow to the project.
Fixes #779

feat: Added cyber-streakglow theme

---

src/translations.php

I made some big changes for this translation. Here's an explanation:
1. **Changes to the translation of `"Longest Streek"` and `"Longest Week Streak"`**
Previously used `"최대"` which literally means `"biggest"`. I changed it to `"최장"` which means `"longest"`. Also, added `"연속"` as the translation of `"streak"`.
2. **Changes to the translation of `"Week Streak"`**
Previously translated as `"주간 기여 수"` which only indicates the weekly contribution amount. I changed it to `"주간 연속 기여수"`. The addition of `"연속"` as a translation of `"streak"`.
3. **Changes to the translation of `"Excluding {days}"`**
Previously translated as `"{days} 제외된"`, which means "excluded {days}" (passive form), it is not precise in conveying the meaning of exclusion. I changed it to `"{days} 제외하고"`.
If this needs to be …

fix: Updated Korean translations

---

src/translations.php

I made a change from `"Tidak termasuk {days}"` to `"Kecuali {days}"`. This was done because the equivalent of `"kecuali"` is more precise and clear to express exclusion in Indonesian. The word `"tidak termasuk"` can cause ambiguity because it literally only states that something is not included, whereas the word `"kecuali"` explicitly indicates that the days are excluded from the calculation or list. Thus, `"Kecuali {days}"` is easier to understand and directly conveys the overall intention of exclusion.
_None_

fix: Updated Indonesian for Excluding translation

---

docs/themes.md
src/themes.php

feat(theme): add Vitesse theme inspired by @antfu's [Vitesse Theme](https://github.com/antfu/vscode-theme-vitesse)
[Demo](https://github-readme-streak-vercel.vercel.app/demo/preview.php?user=&theme=vitesse) 
| Property           | Hex Code                                                              |
| ------------------| ---------------------------------------------------------------------- |
| background         | ![#000000](https://placehold.co/15/000000/000000?text=+) `#000000`    |
| border             | ![#4D9375](https://placehold.co/15/4D9375/000000?text=+) `#4D9375`    |
| stroke             | ![#5D99A9](https://placehold.co/15/5D99A9/000000?text=+) `#5D99A9`    |
| ring               | ![#4D9375](https://placehold.co/15/4D9375/000000?text=+) `#4D9375`    |
| fire …

feat(theme): add Vitesse theme inspired by @antfu's antfu/vscode-theme-vitesse

---

public/404.html

Added custom 404 page that redirects users to the main repository, replacing Vercel's default error page for better user experience.

feat: add custom 404 page with redirect to main repository

---

src/translations.php

Updated the Tamil translation for the phrase "Excluding {days}" to ensure accurate localization.

feat(translations): add Tamil translation for "Excluding {days}"

---

Dockerfile
README.md

This PR adds Docker support to enable easy self-hosting of GitHub Readme Streak Stats. The implementation provides a production-ready, secure Dockerfile with
minimal changes to the codebase, addressing community requests for containerized deployment options.
Fixes #622
**Live demo available at:** https://streak-stats.robbeverhelst.com/demo/
are open for this issue
- Kept changes minimal (2 files) based on feedback from #322
- Dockerfile includes security best practices:
- Disabled directory indexing
- Security headers (X-Content-Type-Options, X-Frame-Options)  
- Minimal attack surface with `--no-install-recommends`
- Proper file permissions
- Full feature compatibility including SVG and PNG rendering
- Kubernetes manifests available for separate PR if desired

feat: Add Docker support
