DenverCoder1/github-readme-streak-stats

- README.md
- src/card.php
- themes/README.md
> 🖼 Added hide borders options and themes docs

- docs/themes/README.md
Updated theme docs to have `ads-juicy-fresh` theme and `black-ice`
> 🖼 Added new themes to docs

- src/card.php
- src/stats.php
Generate error card when error occurred, without displaying text message
> Use SVG to display errors #24

- src/card.php
Added some animation. Mostly fadeIn animations.
You can check this directly at [here.](https://github-streak.herokuapp.com/PhoenixCreation)
WARNING:
I haven't tested this... Reason: I don't have php setup.
If you find problem you can refer [this.](https://github.com/PhoenixCreation/Github-Streak/blob/8189049c37307a07e19323807a5faca2c7d28b11/index.js#L204)
Some problems:
- The ring around current streak's stroke-offset start from right-middle so it can't be animated like full circle filling.
- Animating fire icon to look like real fire wasn't inside my skill level.
I will be available on discord in ProgrammingHumor Server as a PhoenixCreation.
>  ↔️ Added animations on start. 

- src/stats.php
Fixed issue with GitHub returning inconsistent contribution counts.
Closes #34.
> Change to dates to end with 12-31

- README.md
Added emoji to readme section headers, replaced parameter lists with tables for readability, removed contact links for simplicity.
Fixes #38
> 📜 Added emoji and tables to readme

- src/stats.php
Simplified stats logic and changed variable names
> 🧹 Simplified stats logic and formatting

- README.md
Cleaned up some formatting in the Readme
> 🧹 Cleaner formatting

- README.md
- demo/css/style.css
- demo/demo.php
- demo/index.php
- demo/js/script.js
- src/index.php
Added a demo site for previewing streak stats cards and customizing options
Fixes #33
> 💻 Added Demo Site

- src/.htaccess
Removed htaccess to test changes to directories
> 🚮 Removed htaccess

- README.md
Added Screenshot of Demo Site to Readme
> 🖼 Added screenshot of demo site to readme

- src/demo/css/style.css
- src/demo/index.php
- src/demo/js/script.js
Added input validation to Demo Site
Fixes #48 
If you have changed a feature of the stats cards, please describe the tests you made to verify your changes.
> ✅ Added input validation to demo site

- src/demo/css/style.css
- src/demo/css/toggle-dark.css
- src/demo/index.php
- src/demo/js/toggle-dark.js
Added dark mode to demo site
Fixes #46 
If you have updated the design or appearance, please include a screenshot of your changes.
> 😎 Added dark mode to demo site

- README.md
Added a gif to the demo site
Fixes #62
> 👾 Added animated GIF of the Demo Site

- docs/themes/README.md
- src/themes.php
Hi, I added and tested a new `dark-smoky` theme to the list. The tests was successful :+1: 
Closes #61 
Fixes # ( #61 )
If you have changed a feature of the stats cards, please describe the tests you made to verify your changes.
`dark-smoky`
> 🎨 Added new theme `dark-smoky`

- src/index.php
Please include a summary of the change and which issue is fixed.
Fixes #64 
If you have changed a feature of the stats cards, please describe the tests you made to verify your changes.
If you have updated the design or appearance, please include a screenshot of your changes.
> Added redirect

- composer.json
- tests/OptionsTest.php
Fix dependency in composer.json for Heroku
> Fix dependency in composer.json for Heroku

- docs/themes/README.md
- src/themes.php
> 🎨 Added monokai-metallian theme

- src/themes.php
- tests/OptionsTest.php
This new test will ensure that themes cannot have parameters which do not exist.
> Test that themes don't have extra parameters

- README.md
- docs/themes/README.md
Organized the themes docs to be in a table instead of a vertical list
> 🍱 Organized themes in a table

- .github/ISSUE_TEMPLATE/theme.md
> Theme Issue Template

- src/demo/css/style.css
- src/demo/index.php
- tests/StatsTest.php
Updated buttons to use https://buttons.github.io/ since they look nicer and are aligned better
Before:
After:
> Update site buttons with buttons.github.io

- README.md
Added details for Heroku deployment and simplified steps for creating token.
Fixes #96
> Added details for deploying to Heroku

- docs/themes/README.md
- src/themes.php
> 🌎 Added earth theme

- README.md
Added instructions for deploying Streak Stats to Zeet
> 📤 Add Zeet instructions

- README.md
Added logos for Heroku and Zeet
> 🚀 Added logos for deployment options

- README.md
- vercel.json
🔼 Added instructions for Vercel deployment
⚙️ Added vercel config for PHP
> 🔼 Added instructions for Vercel deployment

- README.md
- vercel.json
Reverts DenverCoder1/github-readme-streak-stats#102
It seems Vercel won't work with PHP runtime unless functions are in api directory
> Revert "🔼 Added instructions for Vercel deployment"

- docs/themes/README.md
- src/themes.php
This PR is regarding the new theme for which i have already created an issue. Please do review and let me know if you need any changes. I have already tested it locally.
Fixes #115  
Thank you
> deep-Blue theme

- .github/workflows/release.yml
- .github/workflows/stale.yml
release.yml - automated releases
stale.yml - mark old issues and prs as stale
> Added release and stale github actions

- docs/themes/README.md
- src/themes.php
This PR includes [Holi theme](https://github.com/AyushSaini00/holi-theme) to the project.
Fixes #126
Thank you for developing the project. Looking forward!!! 🙌
> holi-theme colors

- docs/themes/README.md
- src/themes.php
> New Theme Ayu-Light

- docs/themes/README.md
- src/themes.php
Add Noctis minimus theme
Fixes #32
> Add noctis-minimus theme

- composer.json
> Composer fix

- docs/themes/README.md
- src/themes.php
Add JavaScript-dark theme
Fixes #32
> Add Javascript-dark theme

- .env.example
- .gitignore
- README.md
- composer.json
- composer.lock
- src/index.php
- src/stats.php
- tests/StatsTest.php
Fixes #154
- [ X ] New feature (added a non-breaking change which adds functionality)
- [ X] Tested locally with a valid username
- [ X] Tested locally with an invalid username
- [ X] Ran tests with `composer test`
- [ X] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [ X] The code is properly formatted and is consistent with the existing code style
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
> Refactor config.php

- src/card.php
> Get imagick image from file instead of blob

- src/card.php
This reverts commit 78322f05f569bfe1f83293f281848c7b9d3257ae.
It did not solve the issue.
> Revert "Get imagick image from file instead of blob (#166)"

- docs/themes/README.md
- src/themes.php
Add github-dark
Fixes #32 #173  
##
Screenshots
> Add github-dark theme

- docs/themes/README.md
- src/themes.php
Add github-light theme
Fixes #32 #173
> Add github-light theme

- src/card.php
- src/stats.php
> Add link to rate-limit discussion in rate-limit error

- docs/themes/README.md
- src/themes.php
hey! @DenverCoder1 
I have contributed two new themes namely **elegant** and **leafy**. Please review them.
Fixes #197
Thank you for programming this contribution and coding activity stat. It not only looks good but also persuades programmers to keep coding and contributing more to their stats.
Thanks & Regards.
> feat: Contributed themes - elegant & leafy

- src/card.php
- src/demo/css/style.css
- src/demo/index.php
- tests/expected/test_card.svg
- tests/expected/test_date_card.svg
- tests/expected/test_error_card.svg
**Linked to issue #204**
**Summary**
Okay, I think I have managed to do a full update of the font stack. I basically just did a repo wide search for the words 'font' and 'font-family' and updated everything that I found. Let me know if I missed something.
**Updates**
I updated the font stack from `Open Sans, Roboto, system-ui, sans-serif` to `Segoe UI, Ubuntu, sans-serif` and removed imports for `Open Sans` because its not being used anymore.
> feat: Update to use consistent font-family

- CONTRIBUTING.md
Hey! @DenverCoder1 
I have come across a few grammatical errors in `CONTRIBUTING.md` I am listing them in below bullet points. Please review this contribution.
- **Make a copy** of  ~`.env.example`~ **the `.env.example`** named `.env` in the root directory and add **your token** after `TOKEN=`.
- Create a new branch. Use its name to identify the issue **~your~ you're** addressing.
- It will create a new branch with **~name~ the name** Branch_Name and switch to that branch
Thanks
> docs(contributing): CONTRIBUTING.md grammar

- docs/themes/README.md
- src/themes.php
Added themes is name "navy-gear" and fixed
> feat: Adds navy-gear theme

- docs/themes/README.md
- src/themes.php
Created github dark blue theme. Since the current github dark theme is green, I made a blue one. 
Fixes # 
Closes #218
> GitHub Dark Blue

- docs/themes/README.md
- src/themes.php
I think this theme should be here too 🐱‍💻 😋
> feat: Adds hacker theme

- docs/themes/README.md
- src/themes.php
> feat: Adds Garden Theme 

- src/translations.php
- tests/expected/test_locale_card.svg
Thanks u/Syruss_ and u/ringed_seal for the help on [Reddit](https://www.reddit.com/r/translator/comments/uyqxpg/english_japanese_total_contributions_current/)
> fix: update Japanese translations

- src/translations.php
> feat: Spanish locale 🇪🇸🇪🇸🇪🇸

- src/translations.php
Fixes # 
Added German translation
> feat: Added German translation

- src/translations.php
references #236
- [:heavy_check_mark: ] Tested locally with a valid username
- [:heavy_check_mark:] Tested locally with an invalid username
- [:heavy_check_mark:] Ran tests with `composer test`
- [:heavy_check_mark:] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [:heavy_check_mark: ] The code is properly formatted and is consistent with the existing code style
- [ :heavy_check_mark:] My changes generate no new warnings
[![ss1.png](https://i.postimg.cc/CxyCzCZV/ss1.png)](https://postimg.cc/crmtznMD)
> Added Turkish translations

- src/card.php
- src/translations.php
- tests/TranslationsTest.php
- tests/expected/test_locale_ja_card.svg
> feat: Added Chinese and support "Present" translations

- src/translations.php
> fix: Update translation pt-br in translations.php

- src/translations.php
Added German translation for "Present"
Fixes #
> fix: Updated German translation with "Present"

- src/demo/index.php
- src/demo/js/script.js
> fix(demo): fill missing php export colors from selected theme

- src/translations.php
> Add Indonesian Translation

- src/translations.php
> feat: added hindi translation

- src/translations.php
> feat: Added dutch translation

- src/translations.php
Fixes # 
- [ x] Bug fix (added a non-breaking change which fixes an issue)
> feat: Added Italian translation

- composer.lock
> chore: Update composer.lock

- .github/workflows/phpunit-ci-coverage.yml
- CONTRIBUTING.md
- README.md
- composer.json
- composer.lock
Replace imagick dependency with inkscape
Ref: #298
> chore: Replace imagick dependency with inkscape

- docs/themes.md
- src/themes.php
> feat: add git-dark theme

- docs/themes.md
- src/themes.php
> feat: add python-dark theme

- src/translations.php
> feat: add French translation

- .github/workflows/prettier.yml
- composer.json
- composer.lock
- src/card.php
Update prettier workflow since the old one does not commit changes
> ci: Update prettier workflow

- .gitignore
- src/translations.php
🔡 Added Kannada Translations
Fixes # 0
> feat: Added Kannada Translations

- src/translations.php
> feat: Added Vietnamese Translations

- src/translations.php
> feat: Added Danish translation

- README.md
Updated readme layout and details
> docs(readme): Readme layout enhancements and added notes

- src/translations.php
> fix: Responsiveness made to Tamil translation

- src/translations.php
This PR will introduce the required translation in _Bengali_
Fixes #236
> feat: Added Bangla Translations

- docs/themes.md
- src/themes.php
> feat: Added "violet-punch" streak stats theme

- README.md
added hyperlinks to allow the reader to open an issue / pull request straight from the readme
Fixes # 1
> docs(readme): Added hyperlinks for issues and PRs

- README.md
- src/card.php
- src/demo/index.php
- src/demo/js/script.js
- src/demo/preview.php
- src/index.php
- src/stats.php
- src/translations.php
- tests/RenderTest.php
- tests/StatsTest.php
- tests/TranslationsTest.php
- tests/expected/test_stats.json
> feat: Add weekly contribution mode

- .github/workflows/translation-progress.yml
- README.md
- scripts/translation-progress.php
Adds translation progress to the readme
> docs: Add translation progress

- README.md
Adds details to readme about issue #32
> docs(readme): Add Issue 32 link in themes

- src/translations.php
Added Korean translations for week streak and longest week streak
> Added Korean translations

- src/translations.php
* Added in Arabic translations;
* Fixed and finished up the Bangla translations;
* Finished up the Hindi translations;
* Finished up the Spanish translations.
> feat: Added translations for Arabic, Bangla, Hindi, Spanish

- src/translations.php
Defining and adding [Persian](https://en.wikipedia.org/wiki/Persian_language) words
> feat: Added Persian (fa) translations

- src/translations.php
- **correct 2 translation lines in Hindi.**
> feat: Added Marathi and corrected Hindi translation

- README.md
> docs(readme): Added steps for deploying to Vercel

- src/translations.php
> feat: Update Russian translations

- README.md
> docs(readme): Update vercel instructions with Git note and env image

- README.md
> docs(readme): Update Vercel information

- src/translations.php
> Added Pashto translations

- src/translations.php
The Arabic text is not correct as a grammar and syntax
> fix: Fixed Arabic translations

- src/translations.php
> Added Bulgarian translations

- src/translations.php
> Add Ukrainian Language

- src/stats.php
> fix: Handle curl errors for single graphQL

- src/stats.php
> fix: Don't retry if rate limit exceeded

- src/stats.php
> perf: Combine first two requests and refactor

- src/card.php
- src/stats.php
> refactor: Update types and docstrings

- src/translations.php
Just a small change in order to improve the spanish translation.
> fix: Updated Spanish translation

- src/translations.php
Added new and updated the existing kannada("kn") language translations...
issue #236
Updated a previously existing translation to be more precise and added new translations.
> feat: Updated Kannada translations

- src/translations.php
Updated `it` translation
Fixes #236
> feat: Updated Italian translations

- src/translations.php
> feat: Updates Vietnamese translations

- src/stats.php
> fix: Catch error if failed to get contributions twice

- src/translations.php
> feat: Updated German translations

- src/translations.php
Updated `id` transaltion
[#236](https://github.com/DenverCoder1/github-readme-streak-stats/issues/236)
> feat: Updated Indonesian Translations

- .env.example
- src/translations.php
Translation to Haitian Creole
- [ ✅] Tested locally with a valid username
- [ ✅] Tested locally with an invalid username
- [ ✅] Ran tests with `composer test`
- [✅ ] Added or updated test cases to test new features
- [✅ ] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [✅ ] The code is properly formatted and is consistent with the existing code style
- [✅ ] My changes generate no new warnings
> feat: Added Haitian Creole translations

- src/demo/js/script.js
Fixes #434 
https://user-images.githubusercontent.com/60817786/215318241-8ed9288d-951a-4e12-8e1a-b0703398a45f.mp4
> feat: Update stats whenever form input changes

- src/demo/index.php
- src/demo/js/script.js
Fixes #433
https://user-images.githubusercontent.com/60817786/215278598-5ce00e22-f405-470b-8cc5-9e1913f563c2.mp4
> feat: Clear advanced props button

- src/translations.php
Added Sanskrit translations to translations.php
Fixes # Issue 236
> feat: Added Sanskrit translations

- src/translations.php
> feat: Updated Tamil translations

- src/translations.php
> feat: Updated Turkish translations

- README.md
- src/card.php
- src/demo/index.php
- src/demo/js/script.js
- tests/RenderTest.php
> feat: Add `disable_animations` parameter

- docs/themes.md
- src/themes.php
> feat: Added rising-sun theme

- docs/themes.md
> docs(themes): Added info about normalized theme names

- src/translations.php
> feat: Added Armenian translations

- src/translations.php
Added translations for Kinyarwanda
Fixes #236
> feat: Add kinyarwanda translations

- src/demo/css/style.css
- src/demo/index.php
- src/demo/js/script.js
> feat(demo): Support solid and gradient by toggle

- README.md
- src/card.php
- src/demo/index.php
- tests/expected/test_card.svg
Adds ability to hide columns:
|         Parameter          |                     Details                      |                                              Example                                               |
| :------------------------: | :----------------------------------------------: | :------------------------------------------------------------------------------------------------: |
| `hide_total_contributions` | Hide the total contributions (Default: `false`)  |                                         `true` or `false`                                          |
|   `hide_current_streak`    |    Hide the current streak (Default: `false`)    |                                         `true` or `false`                                          |
|   `hide_longest_streak`    | …
> feat: Add flags to hide specified columns

- src/demo/css/style.css
- src/demo/index.php
- src/demo/js/script.js
Improved accessibility by using labels and groups according to documentation (label "for" should match the "id" of an input, aria-labelledby can be used for [labelling groups of inputs](https://stackoverflow.com/a/45677146/11608064))
> refactor: Improve label accessibility and demo initialization

- src/translations.php
Updated the Urdu Translation which was 86% complete before. 
Fixes # 236
> feat: Updated Urdu translations

- README.md
> docs(readme): Update deployment method information

- src/translations.php
Translation of the new word to ukrainian
#236 
Translated word "Excluding" to Ukrainian.
> feat: Updated Ukrainian translations

- src/translations.php
> feat: Added Amharic Translations

- src/translations.php
Added necessary lines of code for Serbian language
> feat: Added Serbian translations

- src/translations.php
Updated Greek translation by adding the new word `Excluding`.
> feat: Updated Greek translations

- src/translations.php
updated korean translation by adding `excluding`
> feat: Updated Korean translations

- src/demo/css/style.css
- src/demo/index.php
- src/demo/js/script.js
> feat(demo): Support hiding sections on demo site

- src/card.php
> fix: Prevent error when all columns are hidden

- src/translations.php
> chore: 🌐 add Nepali translations

- src/translations.php
> Add Catalan support

- src/translations.php
Added Hungarian translation to translations.php
#236
> feat: Added Hungarian translations

- src/translations.php
Just updated one translation to a more natural language in brazilian portuguese.
> fix: Corrected Portuguese translation

- docs/themes.md
- src/themes.php
Added burnt-neon theme to themes.php and updated themes.md respectively.
Fixes #541
Closes #541
Docs/ themes.md changed:
> feat: Added burnt-neon theme

- src/translations.php
added sanskrit translation for excluding -> बहिष्करणम्
> feat: Added Sanskrit translation for excluding

- .github/workflows/prettier.yml
> ci: Fix prettier using earlier version

- .github/workflows/prettier.yml
- docs/themes.md
> ci(prettier): Include git diff in Prettier workflow output

- README.md
> docs(readme): Improvements to Vercel deployment instructions

- README.md
Moved the note higher and split steps into two option sections.
> docs(readme): Restructure Vercel documentation

- app.json
The free formation is no longer valid, so this needs to be changed
> chore: Update app.json Heroku formation

- README.md
> docs(readme): Enhance deployment instructions and add video

- README.md
> docs(readme): Move Vercel png warning higher up

- docs/faq.md
> docs(faq): Add self-hosting to FAQ

- src/translations.php
> Added Thai translations

- src/translations.php
Add Arabic, Japanese, Polski, Svenska, and Kiswahili translations for Excluding
> feat: Add Arabic translation for Excluding

- src/translations.php
> feat: Added Filipino translations

- docs/themes.md
- src/themes.php
Add iceberg theme
|             Theme             |                                                          Preview                                                          |
| :---------------------------: | :-----------------------------------------------------------------------------------------------------------------------: |
|           `iceberg`           | ![image](https://github.com/DenverCoder1/github-readme-streak-stats/assets/86386385/912d8f6a-ba21-4668-9109-300c67a1f1c2) |
> feat: Add iceberg theme

- src/translations.php
> feat: Added excluding in Hindi

- src/translations.php
Updated `ru` translation
ref #236
> feat: Updated Russian translations

- src/translations.php
> feat: Added Javanese translation

- src/translations.php
Add missing translation for the Marathi language.
"Excluding {days}" => "वगळून {days}"
ref #236
>
> feat: Add missing translation for Marathi

- README.md
> docs: move images outside quote since it no longer displays correctly

- src/translations.php
added a translation for 'exclusing' in pashto in translation.php
Translation.php was missing translation for "excluding" in pashto. 
It was added
Fixes # 
no test, just updated documentation
> feat: Update Pashto Translations

- src/translations.php
Add Norwegian translation #236.
> Add Norwegian translation

- src/translations.php
The PR adds Sindhi (PK) translations to translations.php
Fixes # [236](https://github.com/DenverCoder1/github-readme-streak-stats/issues/236)
> feat: Added Sindhi (PK) translation

- api/themes.php
- composer.json
- composer.lock
- docs/themes.md
- vercel.json
I fixed #642 by updating the vercel-php version
Fixes #642 
Before:
After:
> fix: Updated the vercel-php version

- .github/workflows/phpunit-ci-coverage.yml
- CONTRIBUTING.md
- composer.json
- composer.lock
> chore: Update PHP version to 8.2

- src/translations.php
- Added translations for Gujarati language (Completed)
> Added translations for Gujarati language

- src/translations.php
> Update translations.php - Added missing Polish (pl) translation for Excluding {days} property

- docs/themes.md
- src/themes.php
Add taiga theme, colors are from [here](https://github.com/daniilshat/taiga-theme).
> feat: add taiga theme

- src/demo/index.php
> fix: Use new css.gg cdn link

- src/translations.php
Added Bhojpuri (India) translations for contribution streak features, including terms like "Total Contributions," "Current Streak," and others.  
Fixes #
> Added Bhojpuri (India) translations

- src/translations.php
I tried to perfect the translation into Malay for `"Excluding {days}"`. The case is more or less similar as in PR #785.
_None_
> fix: Updated Malay for Excluding translation

- src/translations.php
> fix(translations):  Bengali ("bn") - add "Excluding {days}" & fix inconsistent translations of "streak"

- src/translations.php
> Added Malay(Indonesia)

- src/translations.php
> Add Malayalam translations for contributions

- src/translations.php
Punjabi Language (pa):
- "Total Contributions" => ਕੁੱਲ ਯੋਗਦਾਨ
- "Current Streak" => ਮੌਜੂਦਾ ਲਗਾਤਾਰ ਦਿਨ
- "Longest Streak" => ਸਭ ਤੋਂ ਲੰਬੀ ਲਗਾਤਾਰ ਸਿਰੀਂ
- "Week Streak" => ਹਫ਼ਤਾ ਲਗਾਤਾਰ ਸਿਰੀਂ
- "Longest Week Streak" => ਸਭ ਤੋਂ ਲੰਬੀ ਹਫ਼ਤਾਵਾਰੀ ਸਿਰੀਂ
- "Present" => ਮੌਜੂਦ
- "Excluding {days}" => {days} ਨੂੰ ਛੱਡ ਕੇ
> Punjabi - (pa) language translation added
